create table if not exists historial_sifen_comprobantes (
    id bigint generated by default as identity primary key,
    comprobante_id bigint not null references comprobantes(id) on delete cascade,
    usuario_id bigint null,
    estado_sifen varchar(30) not null,
    aceptado boolean not null default false,
    estado_respuesta varchar(100) null,
    codigo_respuesta varchar(100) null,
    mensaje_respuesta varchar(500) null,
    tracking_id varchar(100) null,
    cdc varchar(100) null,
    numero_lote varchar(100) null,
    fecha_hora timestamp without time zone not null default timezone('utc', now()),
    fecha_respuesta timestamp with time zone null,
    detalle varchar(1000) null,
    respuesta_cruda varchar(4000) null
);

create index if not exists ix_historial_sifen_comprobantes_comprobante_id
    on historial_sifen_comprobantes (comprobante_id);

create index if not exists ix_historial_sifen_comprobantes_comprobante_fecha
    on historial_sifen_comprobantes (comprobante_id, fecha_hora desc);

create index if not exists ix_historial_sifen_comprobantes_tracking_id
    on historial_sifen_comprobantes (tracking_id);

create index if not exists ix_historial_sifen_comprobantes_cdc
    on historial_sifen_comprobantes (cdc);