BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- TERCEROS: PERSONERÍA Y DATOS FISCALES BASE
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS tipo_personeria character varying(20) NOT NULL DEFAULT 'JURIDICA';

ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS nombre character varying(150);

ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS apellido character varying(150);

ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS es_entidad_gubernamental boolean NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS clave_fiscal character varying(50);

ALTER TABLE IF EXISTS terceros
    ADD COLUMN IF NOT EXISTS valor_clave_fiscal character varying(30);

-- ─────────────────────────────────────────────────────────────────────────────
-- PERFIL COMERCIAL AMPLIADO
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS terceros_perfiles_comerciales (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    zona_comercial_id bigint,
    rubro character varying(100),
    subrubro character varying(100),
    sector character varying(100),
    condicion_cobranza character varying(150),
    riesgo_crediticio character varying(20) NOT NULL DEFAULT 'NORMAL',
    saldo_maximo_vigente numeric(18,4),
    vigencia_saldo character varying(100),
    condicion_venta character varying(150),
    plazo_cobro character varying(150),
    facturador_por_defecto character varying(150),
    minimo_factura_mipymes numeric(18,4),
    observacion_comercial character varying(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_perfiles_comerciales PRIMARY KEY (id),
    CONSTRAINT fk_terceros_perfiles_comerciales_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE,
    CONSTRAINT fk_terceros_perfiles_comerciales_zonas_comerciales_zona_comercial_id FOREIGN KEY (zona_comercial_id) REFERENCES zonas_comerciales (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_terceros_perfiles_comerciales_tercero_id
    ON terceros_perfiles_comerciales (tercero_id);

CREATE INDEX IF NOT EXISTS ix_terceros_perfiles_comerciales_zona_comercial_id
    ON terceros_perfiles_comerciales (zona_comercial_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONTACTOS MÚLTIPLES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS terceros_contactos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    cargo character varying(100),
    email character varying(150),
    telefono character varying(50),
    sector character varying(100),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_contactos PRIMARY KEY (id),
    CONSTRAINT fk_terceros_contactos_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_contactos_tercero_orden
    ON terceros_contactos (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_contactos_tercero_principal
    ON terceros_contactos (tercero_id, principal);

-- ─────────────────────────────────────────────────────────────────────────────
-- SUCURSALES / PUNTOS DE ENTREGA
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS terceros_sucursales_entrega (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    descripcion character varying(200) NOT NULL,
    direccion character varying(300),
    localidad character varying(150),
    responsable character varying(150),
    telefono character varying(50),
    horario character varying(150),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_sucursales_entrega PRIMARY KEY (id),
    CONSTRAINT fk_terceros_sucursales_entrega_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_sucursales_entrega_tercero_orden
    ON terceros_sucursales_entrega (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_sucursales_entrega_tercero_principal
    ON terceros_sucursales_entrega (tercero_id, principal);

-- ─────────────────────────────────────────────────────────────────────────────
-- TRANSPORTES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS terceros_transportes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    transportista_id bigint,
    nombre character varying(200) NOT NULL,
    servicio character varying(150),
    zona character varying(150),
    frecuencia character varying(150),
    observacion character varying(500),
    activo boolean NOT NULL DEFAULT TRUE,
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_transportes PRIMARY KEY (id),
    CONSTRAINT fk_terceros_transportes_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE,
    CONSTRAINT fk_terceros_transportes_transportistas_transportista_id FOREIGN KEY (transportista_id) REFERENCES transportistas (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_tercero_orden
    ON terceros_transportes (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_tercero_principal
    ON terceros_transportes (tercero_id, principal);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_transportista_id
    ON terceros_transportes (transportista_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- VENTANAS DE COBRANZA
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS terceros_ventanas_cobranza (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    dia character varying(50) NOT NULL,
    franja character varying(100),
    canal character varying(100),
    responsable character varying(150),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_ventanas_cobranza PRIMARY KEY (id),
    CONSTRAINT fk_terceros_ventanas_cobranza_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_ventanas_cobranza_tercero_orden
    ON terceros_ventanas_cobranza (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_ventanas_cobranza_tercero_principal
    ON terceros_ventanas_cobranza (tercero_id, principal);

COMMIT;
