BEGIN;

CREATE TABLE IF NOT EXISTS terceros_contactos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    cargo character varying(100),
    email character varying(150),
    telefono character varying(50),
    sector character varying(100),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_contactos PRIMARY KEY (id),
    CONSTRAINT fk_terceros_contactos_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_contactos_tercero_orden
    ON terceros_contactos (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_contactos_tercero_principal
    ON terceros_contactos (tercero_id, principal);

COMMIT;
