BEGIN;

CREATE TABLE IF NOT EXISTS terceros_perfiles_comerciales (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    zona_comercial_id bigint,
    rubro character varying(100),
    subrubro character varying(100),
    sector character varying(100),
    condicion_cobranza character varying(150),
    riesgo_crediticio character varying(20) NOT NULL DEFAULT 'NORMAL',
    saldo_maximo_vigente numeric(18,4),
    vigencia_saldo character varying(100),
    condicion_venta character varying(150),
    plazo_cobro character varying(150),
    facturador_por_defecto character varying(150),
    minimo_factura_mipymes numeric(18,4),
    observacion_comercial character varying(1000),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_perfiles_comerciales PRIMARY KEY (id),
    CONSTRAINT fk_terceros_perfiles_comerciales_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE,
    CONSTRAINT fk_terceros_perfiles_comerciales_zonas_comerciales_zona_comercial_id FOREIGN KEY (zona_comercial_id) REFERENCES zonas_comerciales (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_terceros_perfiles_comerciales_tercero_id
    ON terceros_perfiles_comerciales (tercero_id);

CREATE INDEX IF NOT EXISTS ix_terceros_perfiles_comerciales_zona_comercial_id
    ON terceros_perfiles_comerciales (zona_comercial_id);

COMMIT;
