BEGIN;

CREATE TABLE IF NOT EXISTS terceros_transportes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    transportista_id bigint,
    nombre character varying(200) NOT NULL,
    servicio character varying(150),
    zona character varying(150),
    frecuencia character varying(150),
    observacion character varying(500),
    activo boolean NOT NULL DEFAULT TRUE,
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_transportes PRIMARY KEY (id),
    CONSTRAINT fk_terceros_transportes_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE,
    CONSTRAINT fk_terceros_transportes_transportistas_transportista_id FOREIGN KEY (transportista_id) REFERENCES transportistas (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_tercero_orden
    ON terceros_transportes (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_tercero_principal
    ON terceros_transportes (tercero_id, principal);

CREATE INDEX IF NOT EXISTS ix_terceros_transportes_transportista_id
    ON terceros_transportes (transportista_id);

COMMIT;
