BEGIN;

CREATE TABLE IF NOT EXISTS terceros_sucursales_entrega (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    descripcion character varying(200) NOT NULL,
    direccion character varying(300),
    localidad character varying(150),
    responsable character varying(150),
    telefono character varying(50),
    horario character varying(150),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_sucursales_entrega PRIMARY KEY (id),
    CONSTRAINT fk_terceros_sucursales_entrega_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_sucursales_entrega_tercero_orden
    ON terceros_sucursales_entrega (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_sucursales_entrega_tercero_principal
    ON terceros_sucursales_entrega (tercero_id, principal);

COMMIT;
