BEGIN;

CREATE TABLE IF NOT EXISTS terceros_ventanas_cobranza (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tercero_id bigint NOT NULL,
    dia character varying(50) NOT NULL,
    franja character varying(100),
    canal character varying(100),
    responsable character varying(150),
    principal boolean NOT NULL DEFAULT FALSE,
    orden integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    created_by bigint,
    updated_by bigint,
    CONSTRAINT pk_terceros_ventanas_cobranza PRIMARY KEY (id),
    CONSTRAINT fk_terceros_ventanas_cobranza_terceros_tercero_id FOREIGN KEY (tercero_id) REFERENCES terceros (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_terceros_ventanas_cobranza_tercero_orden
    ON terceros_ventanas_cobranza (tercero_id, orden);

CREATE INDEX IF NOT EXISTS ix_terceros_ventanas_cobranza_tercero_principal
    ON terceros_ventanas_cobranza (tercero_id, principal);

COMMIT;
